<?php

namespace MyTwit\MyTwitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TweetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetsRepository extends EntityRepository
{
}
