<?php

namespace MyTwit\MyTwitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TweetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TweetsRepository extends EntityRepository
{
    public function returnNewTweets()
    {
        return $this->findBy(array('answer_for' => 0), array(), 100);
    }
    
    public function returnAnswers($id)
    {
        return $this->findBy(array('answer_for' => $id), array());
    }
}
