MyTwit\MyTwitBundle\Entity\Answers:
    type: entity
    table: null
    repositoryClass: MyTwit\MyTwitBundle\Entity\AnswersRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        content:
            type: string
            length: '255'
        date:
            type: datetime
        hashtags:
            type: text
            nullable: true
    lifecycleCallbacks: {  }
    manyToOne:
        answersFor:
             targetEntity: Tweets
             inversedBy: answersFor
             joinColumn:
                 name: answersFor
                 referencedColumnName: id
        author:
             targetEntity: User
             inversedBy: answersFor
             joinColumn:
                 name: author
                 referencedColumnName: id