MyTwit\MyTwitBundle\Entity\Tweets:
    type: entity
    table: null
    repositoryClass: MyTwit\MyTwitBundle\Entity\TweetsRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        content:
            type: string
            length: '255'
        date:
            type: datetime
        hashtags:
            type: text
            nullable: true
        answer_for:
            type: integer
    lifecycleCallbacks: {  }
    manyToOne:
        author:
             targetEntity: User
             inversedBy: tweets
             joinColumn:
                 name: author
                 referencedColumnName: id