parameters:
#    my_twit_my_twit.example.class: MyTwit\MyTwitBundle\Example

services:
#    my_twit_my_twit.example:
#        class: %my_twit_my_twit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
