services:
  config_helper:
    class: MyTwit\MyTwitBundle\DependencyInjection\ConfigHelper
    arguments: [@doctrine.orm.entity_manager]
    
  users_helper:
    class: MyTwit\MyTwitBundle\DependencyInjection\UsersHelper
    arguments: [@doctrine.orm.entity_manager]
    
  send_mail:
    class: MyTwit\MyTwitBundle\DependencyInjection\Mailer
    arguments: [@doctrine.orm.entity_manager, @config_helper, @mailer]