parameters:
    database_driver:   pdo_mysql
    database_host:     arhi2.linuxpl.info
    database_port:     ~
    database_name:     arhi2_mytwit
    database_user:     arhi2_mytwit
    database_password: mytwit

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
