parameters:
    database_driver:   pdo_mysql
    database_host:     xxx
    database_port:     ~
    database_name:     xxx
    database_user:     xxx
    database_password: xxx

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt
