security:
    encoders:
        MyTwit\MyTwitBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: MyTwit\MyTwitBundle\Entity\User, property: nickname }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path: /
                check_path: login_check
                always_use_default_target_path: true
                default_target_path: /logged/home
            logout:
                path:   /logout
                target: /
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/logged, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }